mod variables;
pub use variables::Variables;
mod integers;
pub use integers::Integers;
mod floats;
pub use floats::FloatingPoint;
mod computations;
pub use computations::Computations;
mod char_bool_unit;
pub use char_bool_unit::CharBoolUnit;
mod expr_stmt;
pub use expr_stmt::ExpressionStatement;
mod func;
pub use func::Functions;
mod own;
pub use own::Ownership;
mod pmove;
pub use pmove::PartialMove;
mod ref_borrow;
pub use ref_borrow::ReferenceBorrowing;
mod comp_type;
pub use comp_type::CompoundTypes;
mod arrays;
pub use arrays::Arrays;
mod slices;
pub use slices::Slices;
mod tuples;
pub use tuples::Tuples;
mod structs;
pub use structs::Structs;
mod enums;
pub use enums::Enums;
mod flows;
pub use flows::ControlFlow;
mod pat_match;
pub use pat_match::PatternMatch;
mod patterns;
pub use patterns::Patterns;
mod methods;
pub use methods::MethodsAndFuncions;
mod generics;
pub use generics::Generics;
mod const_generics;
pub use const_generics::ConstGenerics;
mod traits;
pub use traits::Traits;
mod atypes;
pub use atypes::AssociatedTypes;
mod ctypes;
pub use ctypes::CollectionTypes;
mod vectors;
pub use vectors::Vectors;
mod hashmaps;
pub use hashmaps::HashMaps;
mod type_coerce;
pub use type_coerce::TypeCoercions;
mod from_into;
pub use from_into::FromIntoConversion;
mod others;
pub use others::Others;
mod panics;
pub use panics::Panics;
mod results;
pub use results::Results;
mod fmt_prn;
pub use fmt_prn::FormatPrint;
mod dbg_disp;
pub use dbg_disp::DebugDisplay;
mod lifetimes;
pub use lifetimes::Lifetimes;
mod statics;
pub use statics::StaticLifetimes;
mod closures;
pub use closures::Closures;
mod iterators;
pub use iterators::Iterators;